// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtPLVPXxmj0M3Ldpq5voK67JlPxucy0k',
    appId: '1:726220096485:web:ecc1df51d6be1742ade50c',
    messagingSenderId: '726220096485',
    projectId: 'fir-3c0d1',
    authDomain: 'fir-3c0d1.firebaseapp.com',
    storageBucket: 'fir-3c0d1.firebasestorage.app',
    measurementId: 'G-V4C5D9P657',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ2VobMlCs9Pv4DlFbYC91FrX3ZN8L7YQ',
    appId: '1:726220096485:android:b9f8fcc9aec0f157ade50c',
    messagingSenderId: '726220096485',
    projectId: 'fir-3c0d1',
    storageBucket: 'fir-3c0d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjitHTecv2HBENaOQZZMKgeg3tsdsUyBI',
    appId: '1:726220096485:ios:8d48fa240f588a1fade50c',
    messagingSenderId: '726220096485',
    projectId: 'fir-3c0d1',
    storageBucket: 'fir-3c0d1.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjitHTecv2HBENaOQZZMKgeg3tsdsUyBI',
    appId: '1:726220096485:ios:8d48fa240f588a1fade50c',
    messagingSenderId: '726220096485',
    projectId: 'fir-3c0d1',
    storageBucket: 'fir-3c0d1.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVtPLVPXxmj0M3Ldpq5voK67JlPxucy0k',
    appId: '1:726220096485:web:da9ba97f9e0b8047ade50c',
    messagingSenderId: '726220096485',
    projectId: 'fir-3c0d1',
    authDomain: 'fir-3c0d1.firebaseapp.com',
    storageBucket: 'fir-3c0d1.firebasestorage.app',
    measurementId: 'G-VCSX06F6FN',
  );
}
